#############################################################################
# Makefile for building: piano
# Generated by qmake (3.1) (Qt 5.12.0)
# Project:  ../piano/piano.pro
# Template: app
# Command: /usr/local/qt-5.12.0/5.12.0/gcc_64/bin/qmake -o Makefile ../piano/piano.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../piano -I. -I/usr/local/qt-5.12.0/5.12.0/gcc_64/include -I/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets -I/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtMultimedia -I/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui -I/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtNetwork -I/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/linux-g++
QMAKE         = /usr/local/qt-5.12.0/5.12.0/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/qt-5.12.0/5.12.0/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/qt-5.12.0/5.12.0/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = piano1.0.0
DISTDIR = /users/eleves-a/2017/nicholas-t.setijabudiharsa/build-piano-Desktop_Qt_5_12_0_GCC_64bit-Debug/.tmp/piano1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/qt-5.12.0/5.12.0/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/qt-5.12.0/5.12.0/gcc_64/lib -lQt5Widgets -lQt5Multimedia -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../piano/main.cpp \
		../piano/piano.cpp qrc_audios.cpp \
		moc_piano.cpp
OBJECTS       = main.o \
		piano.o \
		qrc_audios.o \
		moc_piano.o
DIST          = /usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/spec_pre.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/unix.conf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/linux.conf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/sanitize.conf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/gcc-base.conf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/g++-base.conf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/g++-unix.conf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/qconfig.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/qt_functions.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/qt_config.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/spec_post.prf \
		../piano/.qmake.stash \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/toolchain.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/default_pre.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/resolve_config.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/default_post.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/qml_debug.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/warn_on.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/qt.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/resources.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/moc.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/unix/opengl.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/uic.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/unix/thread.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/qmake_use.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/file_copies.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/exceptions.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/yacc.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/lex.prf \
		../piano/piano.pro ../piano/piano.h ../piano/main.cpp \
		../piano/piano.cpp
QMAKE_TARGET  = piano
DESTDIR       = 
TARGET        = piano


first: all
####### Build rules

piano: ui_piano.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../piano/piano.pro /usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/linux-g++/qmake.conf /usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/spec_pre.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/unix.conf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/linux.conf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/sanitize.conf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/gcc-base.conf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/g++-base.conf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/g++-unix.conf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/qconfig.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/qt_functions.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/qt_config.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/toolchain.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/default_pre.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/resolve_config.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/default_post.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/qml_debug.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/warn_on.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/qt.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/resources.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/moc.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/unix/opengl.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/uic.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/unix/thread.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/qmake_use.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/file_copies.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/exceptions.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/yacc.prf \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/lex.prf \
		../piano/piano.pro \
		../piano/audios.qrc \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/lib/libQt5Widgets.prl \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/lib/libQt5Multimedia.prl \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/lib/libQt5Gui.prl \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/lib/libQt5Network.prl \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile ../piano/piano.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/spec_pre.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/unix.conf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/linux.conf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/sanitize.conf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/gcc-base.conf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/g++-base.conf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/common/g++-unix.conf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/qconfig.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_location.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/qt_functions.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/qt_config.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/linux-g++/qmake.conf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/exclusive_builds.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/toolchain.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/default_pre.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/resolve_config.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/default_post.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/qml_debug.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/warn_on.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/qt.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/resources.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/moc.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/unix/opengl.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/uic.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/unix/thread.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/qmake_use.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/file_copies.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/testcase_targets.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/exceptions.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/yacc.prf:
/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/lex.prf:
../piano/piano.pro:
../piano/audios.qrc:
/usr/local/qt-5.12.0/5.12.0/gcc_64/lib/libQt5Widgets.prl:
/usr/local/qt-5.12.0/5.12.0/gcc_64/lib/libQt5Multimedia.prl:
/usr/local/qt-5.12.0/5.12.0/gcc_64/lib/libQt5Gui.prl:
/usr/local/qt-5.12.0/5.12.0/gcc_64/lib/libQt5Network.prl:
/usr/local/qt-5.12.0/5.12.0/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../piano/piano.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile piano

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../piano/audios.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../piano/piano.h $(DISTDIR)/
	$(COPY_FILE) --parents ../piano/main.cpp ../piano/piano.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../piano/piano.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_audios.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_audios.cpp
qrc_audios.cpp: ../piano/audios.qrc \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/bin/rcc \
		../piano/eb5.wav \
		../piano/c3.wav \
		../piano/b5.wav \
		../piano/g3.wav \
		../piano/f5.wav \
		../piano/eb4.wav \
		../piano/ab5.wav \
		../piano/1397558.ico \
		../piano/b4.wav \
		../piano/gb5.wav \
		../piano/f4.wav \
		../piano/eb3.wav \
		../piano/ab4.wav \
		../piano/b3.wav \
		../piano/a5.wav \
		../piano/gb4.wav \
		../piano/f3.wav \
		../piano/ab3.wav \
		../piano/e5.wav \
		../piano/picture.png \
		../piano/a4.wav \
		../piano/gb3.wav \
		../piano/db5.wav \
		../piano/e4.wav \
		../piano/a3.wav \
		../piano/db4.wav \
		../piano/e3.wav \
		../piano/d5.wav \
		../piano/db3.wav \
		../piano/d4.wav \
		../piano/c6.wav \
		../piano/bb5.wav \
		../piano/d3.wav \
		../piano/c5.wav \
		../piano/bb4.wav \
		../piano/g5.wav \
		../piano/c4.wav \
		../piano/bb3.wav \
		../piano/g4.wav
	/usr/local/qt-5.12.0/5.12.0/gcc_64/bin/rcc -name audios ../piano/audios.qrc -o qrc_audios.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++11 -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_piano.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_piano.cpp
moc_piano.cpp: /usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QMainWindow \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qmainwindow.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qtguiglobal.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qglobal.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qconfig.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qtcore-config.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qsystemdetection.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qprocessordetection.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qtypeinfo.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qsysinfo.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qlogging.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qflags.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qatomic.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qbasicatomic.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qgenericatomic.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qglobalstatic.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qmutex.h \
		../piano/new \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qnumeric.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qversiontagging.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qtgui-config.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qwidget.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qwindowdefs.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qobjectdefs.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qnamespace.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qobject.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstring.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qchar.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qbytearray.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qrefcount.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qarraydata.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringliteral.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringview.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringbuilder.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qlist.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qalgorithms.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qiterator.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qhashfunctions.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qpair.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qbytearraylist.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringlist.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qregexp.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringmatcher.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qcoreevent.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qscopedpointer.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qmetatype.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qobject_impl.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qmargins.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpaintdevice.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qrect.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qsize.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qpoint.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpalette.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qcolor.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qrgb.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qrgba64.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qbrush.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qvector.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qmatrix.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpolygon.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qregion.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qdatastream.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qiodevice.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qline.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qtransform.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpainterpath.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qimage.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpixelformat.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpixmap.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qsharedpointer.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qshareddata.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qhash.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qfont.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qfontmetrics.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qfontinfo.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qcursor.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qkeysequence.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qevent.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qvariant.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qmap.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qdebug.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qtextstream.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qlocale.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qset.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qurl.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qurlquery.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qfile.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qfiledevice.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qvector2d.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qtouchdevice.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qtabwidget.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qicon.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/QStringList \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/QDir \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qdir.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qfileinfo.h \
		../piano/piano.h \
		moc_predefs.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/bin/moc
	/usr/local/qt-5.12.0/5.12.0/gcc_64/bin/moc $(DEFINES) --include /users/eleves-a/2017/nicholas-t.setijabudiharsa/build-piano-Desktop_Qt_5_12_0_GCC_64bit-Debug/moc_predefs.h -I/usr/local/qt-5.12.0/5.12.0/gcc_64/mkspecs/linux-g++ -I/users/eleves-a/2017/nicholas-t.setijabudiharsa/piano -I/usr/local/qt-5.12.0/5.12.0/gcc_64/include -I/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets -I/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtMultimedia -I/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui -I/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtNetwork -I/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore -I. -I/usr/include/c++/4.8.5 -I/usr/include/c++/4.8.5/x86_64-redhat-linux -I/usr/include/c++/4.8.5/backward -I/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I/usr/include ../piano/piano.h -o moc_piano.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_piano.h
compiler_uic_clean:
	-$(DEL_FILE) ui_piano.h
ui_piano.h: ../piano/piano.ui \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/bin/uic
	/usr/local/qt-5.12.0/5.12.0/gcc_64/bin/uic ../piano/piano.ui -o ui_piano.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../piano/main.cpp ../piano/piano.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QMainWindow \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qmainwindow.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qtguiglobal.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qglobal.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qconfig.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qtcore-config.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qsystemdetection.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qprocessordetection.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qtypeinfo.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qsysinfo.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qlogging.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qflags.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qatomic.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qbasicatomic.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qgenericatomic.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qglobalstatic.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qmutex.h \
		../piano/new \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qnumeric.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qversiontagging.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qtgui-config.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qwidget.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qwindowdefs.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qobjectdefs.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qnamespace.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qobject.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstring.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qchar.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qbytearray.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qrefcount.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qarraydata.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringliteral.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringview.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringbuilder.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qlist.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qalgorithms.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qiterator.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qhashfunctions.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qpair.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qbytearraylist.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringlist.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qregexp.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringmatcher.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qcoreevent.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qscopedpointer.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qmetatype.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qobject_impl.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qmargins.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpaintdevice.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qrect.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qsize.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qpoint.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpalette.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qcolor.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qrgb.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qrgba64.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qbrush.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qvector.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qmatrix.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpolygon.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qregion.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qdatastream.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qiodevice.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qline.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qtransform.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpainterpath.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qimage.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpixelformat.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpixmap.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qsharedpointer.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qshareddata.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qhash.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qfont.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qfontmetrics.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qfontinfo.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qcursor.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qkeysequence.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qevent.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qvariant.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qmap.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qdebug.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qtextstream.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qlocale.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qset.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qurl.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qurlquery.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qfile.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qfiledevice.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qvector2d.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qtouchdevice.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qtabwidget.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qicon.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/QStringList \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/QDir \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qdir.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qfileinfo.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QApplication \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qapplication.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qcoreapplication.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qeventloop.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qguiapplication.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qinputmethod.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QSplashScreen \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qsplashscreen.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/QTimer \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qtimer.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qbasictimer.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QDesktopWidget \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../piano/main.cpp

piano.o: ../piano/piano.cpp ../piano/piano.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QMainWindow \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qmainwindow.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qtguiglobal.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qglobal.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qconfig.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qtcore-config.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qsystemdetection.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qprocessordetection.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qtypeinfo.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qsysinfo.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qlogging.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qflags.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qatomic.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qbasicatomic.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qgenericatomic.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qglobalstatic.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qmutex.h \
		../piano/new \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qnumeric.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qversiontagging.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qtgui-config.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qwidget.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qwindowdefs.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qobjectdefs.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qnamespace.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qobject.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstring.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qchar.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qbytearray.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qrefcount.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qarraydata.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringliteral.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringview.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringbuilder.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qlist.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qalgorithms.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qiterator.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qhashfunctions.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qpair.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qbytearraylist.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringlist.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qregexp.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qstringmatcher.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qcoreevent.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qscopedpointer.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qmetatype.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qobject_impl.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qmargins.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpaintdevice.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qrect.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qsize.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qpoint.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpalette.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qcolor.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qrgb.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qrgba64.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qbrush.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qvector.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qmatrix.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpolygon.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qregion.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qdatastream.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qiodevice.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qline.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qtransform.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpainterpath.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qimage.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpixelformat.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qpixmap.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qsharedpointer.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qshareddata.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qhash.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qfont.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qfontmetrics.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qfontinfo.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qcursor.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qkeysequence.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qevent.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qvariant.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qmap.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qdebug.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qtextstream.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qlocale.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qset.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qurl.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qurlquery.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qfile.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qfiledevice.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qvector2d.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qtouchdevice.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qtabwidget.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qicon.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/QStringList \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/QDir \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qdir.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qfileinfo.h \
		ui_piano.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/QVariant \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QApplication \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qapplication.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qcoreapplication.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qeventloop.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qguiapplication.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qinputmethod.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QCommandLinkButton \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qcommandlinkbutton.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qpushbutton.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qabstractbutton.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QFrame \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qframe.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QLabel \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qlabel.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QListWidget \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qlistwidget.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qlistview.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qabstractitemview.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qabstractitemmodel.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qitemselectionmodel.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qstyleoption.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qvalidator.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qregularexpression.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qslider.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qabstractslider.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qstyle.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qtabbar.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qrubberband.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QMenuBar \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qmenubar.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qmenu.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qaction.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qactiongroup.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QPushButton \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QStatusBar \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qstatusbar.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QToolBar \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qtoolbar.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QWidget \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/QVector \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/QStandardItemModel \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtGui/qstandarditemmodel.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/QMessageBox \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qmessagebox.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtWidgets/qdialog.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/QDebug \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/QFile \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/QTextStream \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtMultimedia/QSound \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtMultimedia/qsound.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtMultimedia/qtmultimediaglobal.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtMultimedia/qtmultimedia-config.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/QVectorIterator \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtMultimedia/QMediaPlayer \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtMultimedia/qmediaplayer.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtMultimedia/qmediaobject.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtMultimedia/qmultimedia.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtMultimedia/qmediacontent.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtMultimedia/qmediaresource.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtNetwork/qnetworkrequest.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/QSharedDataPointer \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/QString \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/QUrl \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtMultimedia/qmediaenumdebug.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtCore/qmetaobject.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtMultimedia/qaudio.h \
		/usr/local/qt-5.12.0/5.12.0/gcc_64/include/QtNetwork/qnetworkconfiguration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o piano.o ../piano/piano.cpp

qrc_audios.o: qrc_audios.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_audios.o qrc_audios.cpp

moc_piano.o: moc_piano.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_piano.o moc_piano.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/piano/bin || mkdir -p $(INSTALL_ROOT)/opt/piano/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/piano/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/piano/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/piano/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

