#!/bin/bash

make;

for filename in music/*.mid; do ./midicsv "$filename" "$filename.csv";
done;

for filename in music/*.csv; do mv "$filename" ./; done;

for filename in *.csv; do mv "$filename" csvs; done;

for filename in csvs/*.csv; do ./merge "$filename"; done
